#!/bin/bash

# 
mvn -T 1.5C clean install -Dmaven.test.skip=true
cd target/
mvn install:install-file -Dfile=opensyd-repository-3.1.0.jar -DgroupId=com.venosyd.open -DartifactId=opensyd-repository -Dversion=3.1.0 -Dpackaging=jar
